### ISSUE TITLE
dropdown is broken under 1.13.7

### ISSUE THREAD

**Issue by zakshevskii** [ember-vcl/dropdown#6]
I think that the cause is here
https://github.com/ember-vcl/dropdown/commit/8a58ad527af562cacb108df8b2bcf7d2a609e7c7

Please move release which breaks build to 0.2 branch.

**Comment by OrKoN** [comment]
@piotrpalek please address this issue by releasing incompatible as 0.2.x branch.

**Comment by piotrpalek** [comment]
@OrKoN ok I changed the 0.1.6 release to 0.2.0

**Comment by piotrpalek** [comment]
@OrKoN  or did you mean to move it to a seperate branch altogether?

**Comment by OrKoN** [comment]
Release is fine, thanks!

**Comment by piotrpalek** [comment]
I just realized I have to change the dropdown-menu and other depended packages as well, they are probably broken right now since they have `dropdown@^0.1.6` specified :)

**Comment by OrKoN** [comment]
if you made releases for them, just move them to 0.2.0 as well
